### ISSUE TITLE
is this a reading or a lab?

### ISSUE THREAD

**Issue by geluso** [learn-co-curriculum/fewpjs_object_assign#2]
If this is a reading it's fine.

If it's a lab there's no real instructions.

The following test code doesn't really make any sense, and there's no clear instructions what students should be doing themselves in the lab.

```
    expect(Object).to.exist
    expect(Object).to.equal('toast: "avocado", mimosa: "sunburst orange juice", eggs: "bacon deviled", pancakes: "mini skewers"')
```

Why is it testing `Object`?

It would make more sense if the test checked the results of the `tuesdayMenu` and `wednesdayMenu`objects to make sure they were created with `assign` correctly.

Here's actual student feedback

> Cool. The array element finding lab tests absolutely nothing to do with using `find` or `indexOf`. It doesn't have the student do anything except insert `<div></div>` into the HTML. I'm assuming this is supposed to be discovered using one of these methods, however that is never specified and has nothing to do with the lab readme. and the object assign code along has one test that is annoying and seems to be broken as the students don't have to do any coding, and the result of the provided code appears to return the exact value that the test is looking for, but it still fails.
>
> We're just deleting the test because it's pointless

Thank you!!

**Comment by jenmyers** [comment]
I have resolved this by converting into a readme and have made a note to create a new accompanying lab in the near future.

**Comment by geluso** [comment]
awesome thanks @jenmyers
